Documentation Migration Preview
OpenSimulationInterface/osi-sensor-model-packaging pull request #76
Opened 2021-06-23 10:50 UTC by pmai

Consolidated documentation migration preview updated against master. Will be kept up to date. Probably needs checks that recent v1.1.1 work is fully integrated.

2021-06-24 12:24 UTC, max-rosin approved these changes
From my perspective, everything looks fine.

2021-07-02 13:25 UTC, stefancyliax commented
This is not up to date to branch 68_migrate_spec_topics_to_asciidoc. 
Currently it does not build due to "future_evolution.adoc" missing.

2021-07-02 13:29 UTC, stefancyliax requested changes

2021-07-02 13:29 UTC, stefancyliax commented on doc/osi-sensor-model-packaging_spec.adoc
> +include::./spec/future_evolution.adoc[leveloffset=+2]
This is not up to date to branch 68_migrate_spec_topics_to_asciidoc.
Currently it does not build due to "future_evolution.adoc" missing.

2021-07-07 09:30 UTC, stefancyliax commented
CCB 07.07.2021:
Review will be done by @pmai

2021-09-08 11:29 UTC, closed without merging