Migration to AsciiDoc
OpenSimulationInterface/osi-sensor-model-packaging pull request #77
Opened 2021-07-07 13:42 UTC by max-rosin

This PR is part of the migration to AsciiDoc.

2021-07-08 08:02 UTC, stefancyliax commented
CCB 07.07.2021 addendum:
- Please review @pmai

2021-07-26 19:26 UTC, stefancyliax requested changes
Found some small typos.

2021-07-26 19:26 UTC, stefancyliax commented on doc/spec/sensor_data_inputs.adoc
> +Itdoes not need to copy the contents (zero-copy input).
```suggestion
It does not need to copy the contents (zero-copy input).
```

2021-07-26 19:26 UTC, stefancyliax commented on doc/spec/sensor_data_outputs.adoc
> +Using this convention it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
```suggestion
Using this convention, it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
```

2021-07-26 19:26 UTC, stefancyliax commented on doc/spec/sensor_view_outputs.adoc
> +Using this convention it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
```suggestion
Using this convention, it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
```

2021-07-26 19:26 UTC, stefancyliax commented on doc/spec/traffic_update_outputs.adoc
> +Using this convention it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
```suggestion
Using this convention, it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
```

2021-07-26 19:26 UTC, stefancyliax commented on doc/spec/model_types.adoc
> +However configuration and setup of such FMUs will require manual intervention.
```suggestion
However, configuration and setup of such FMUs will require manual intervention.
```

2021-08-09 08:24 UTC, max-rosin commented on doc/spec/sensor_data_inputs.adoc
> +Itdoes not need to copy the contents (zero-copy input).
Changed.

2021-08-09 08:24 UTC, max-rosin commented on doc/spec/sensor_data_outputs.adoc
> +Using this convention it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
Changed.

2021-08-09 08:25 UTC, max-rosin commented on doc/spec/sensor_view_outputs.adoc
> +Using this convention it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
Changed.

2021-08-09 08:25 UTC, max-rosin commented on doc/spec/traffic_update_outputs.adoc
> +Using this convention it is possible to daisy chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.
Changed.

2021-08-09 08:25 UTC, max-rosin commented on doc/spec/model_types.adoc
> +However configuration and setup of such FMUs will require manual intervention.
Changed.

2021-08-31 18:26 UTC, stefancyliax submitted a review, later dismissed
All feedback was included.

2021-09-08 11:32 UTC, pmai approved these changes
With the given rewrite I think this now transports the same normative details as the previous version while trying to fit better into the new mold of documentation.

2021-09-08 11:33 UTC, pmai commented
@stefancyliax can you review the new changes, if this fits the immediate needs we could merge and release (NB: for release version updates, submodule updates, etc. need to be performed). This still leaves some of the other improvements in the pending PRs out of the release though...

2021-09-08 12:01 UTC, stefancyliax approved these changes
Reviewed rework. Looks fine.

2021-09-08 12:02 UTC, pmai commented
> Reviewed rework. Looks fine.

Can you check whether this also works in terms of the overall documentation pipeline? I have not kept track with that...

2021-09-08 12:05 UTC, stefancyliax commented
> > Reviewed rework. Looks fine.
> 
> Can you check whether this also works in terms of the overall documentation pipeline? I have not kept track with that...

Already on it. OSMP document itself builds fine. Now checking pipeline of osi-documentation.

2021-09-10 12:58 UTC, merged