Added TrafficCommandUpdate to OSMP spec
OpenSimulationInterface/osi-sensor-model-packaging pull request #84
Opened 2022-05-18 07:11 UTC by clemenshabedank

Extended the OSMP spec to account for the newly added [osi_trafficcommandupdate.proto](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/osi_trafficcommandupdate.proto).

2022-05-29 20:46 UTC, pmai requested changes

2022-05-29 20:46 UTC, pmai commented on doc/spec/model_types.adoc
> +They may also produce `osi3::TrafficCommandUpdate` as output to allow a response to that.
```suggestion
They may also produce `osi3::TrafficCommandUpdate` as output to allow status responses to such control messages.
```

2022-05-30 06:50 UTC, stefancyliax commented
OSI CCB 30.05.2022:
- can be merged

2022-05-30 07:52 UTC, pmai approved these changes

2022-05-30 07:53 UTC, merged